# @package _group_
arch:
  scales: 6
  channels: [128, 128, 128, 128, 128, 128]
  skip_channels: [0, 0, 0, 0, 4, 4]
  use_norm: True
  use_sigmoid: True
optim:
  use_scheduler: False
  use_checkpointing: False
  encoder:
    lr: 1e-3
    init_lr: 1e-6
    num_warmup_iter: null
    on_ckpt_return:
      restart_scheduler: True
      multiply_lr_by: 1.
      multiply_init_lr_by: 1.
  decoder:
    lr: 1e-3
    init_lr: 1e-6
    num_warmup_iter: null
    on_ckpt_return:
      restart_scheduler: True
      multiply_lr_by: 1.
      multiply_init_lr_by: 1.
  iterations: 20000
  checkpointing:
    interval: 100
    min_rel_loss_decrease: 0.
  loss_function: mse
  gamma: 1e-4
show_pbar: True
torch_manual_seed: 10
