# @package _group_
arch:
  scales: 6
  channels: [128, 128, 128, 128, 128, 128]
  skip_channels: [0, 0, 0, 0, 4, 4]
  use_norm: True
  use_sigmoid: True
optim:
  encoder:
    lr: 1e-3
    init_lr: 1e-6
    num_warmup_iter: null
  decoder:
    lr: 1e-3
    init_lr: 1e-6
    num_warmup_iter: null
  iterations: 20000
  loss_function: mse
  gamma: 1e-4
show_pbar: True
torch_manual_seed: 10
