# @package _group_
arch:
  scales: 6
  channels: [128, 128, 128, 128, 128, 128]
  skip_channels: [0, 0, 0, 0, 4, 4]
  use_norm: True
  use_sigmoid: True
optim:
  lr: 1e-4
  init_lr: 1e-7
  encoder:
    lr: ${mdl.optim.lr}
    init_lr: ${mdl.optim.init_lr}
    num_warmup_iter: null
  decoder:
    lr: ${mdl.optim.lr}
    init_lr: ${mdl.optim.init_lr}
    num_warmup_iter: null
  iterations: 10000
  loss_function: mse
  gamma: 1e-4
  beta: 1e-4
  beta2: 1e-4
return_iterates_selection:
  mode: 'standard_sequence'
  manual_iters: null
return_iterates_params_selection:
  mode: 'standard_sequence'
  manual_iters: null
show_pbar: True
torch_manual_seed: 10
