defaults:
  - data: standard_ellipses_lotus_20
  - mdl:  model_white
  - trn:  trainer_brightness_contrast_augmentation

pretraining: ???
validation_run: False
save_reconstruction_path: ???
torch_manual_seed_pretrain_init_model: 20
